# Generated by Django 4.1.7 on 2023-09-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transactionlineitem",
            name="remarks",
            field=models.CharField(default="", max_length=200),
        ),
    ]
