# Generated by Django 4.1.7 on 2023-11-28 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanic",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
