# Generated by Django 4.1.7 on 2024-02-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_payable_borrowed_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receivable",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
