# Generated by Django 4.1.7 on 2023-12-03 00:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_mechanic_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="purchaseitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="returneditem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
