# Generated by Django 4.1.7 on 2023-09-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_transactionlineitem_remarks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionlineitem",
            name="remarks",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
