# Generated by Django 4.1.7 on 2023-12-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_product_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
    ]
