# Generated by Django 4.1.7 on 2024-02-22 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_receivable_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payable",
            name="description",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
