# Generated by Django 4.1.7 on 2023-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_transactionlineitem_remarks"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="logo",
            field=models.CharField(default="star", max_length=30),
        ),
    ]
