# Generated by Django 4.1.7 on 2023-12-04 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_sale_customer_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="label_size",
            field=models.IntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
    ]
