# Generated by Django 4.1.7 on 2023-09-27 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_category_logo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Motor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=20)),
                ("maker", models.CharField(blank=True, default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="SparePart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=30)),
            ],
        ),
    ]
