# Generated by Django 4.1.7 on 2024-04-16 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_alter_payable_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receivable",
            name="payment",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="payment_receivable",
                to="myapp.transaction",
            ),
        ),
    ]
