# Generated by Django 4.1.7 on 2023-12-08 00:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_product_label_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="label_format",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
