# Generated by Django 4.1.7 on 2024-04-16 03:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_alter_receivable_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receivable",
            name="payment",
            field=models.ManyToManyField(
                blank=True, related_name="payment_receivable", to="myapp.transaction"
            ),
        ),
    ]
