# Generated by Django 4.1.7 on 2023-09-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0006_mechanic"),
    ]

    operations = [
        migrations.AddField(
            model_name="mechanic",
            name="color",
            field=models.CharField(default="gray", max_length=20),
        ),
    ]
