# Generated by Django 4.1.7 on 2023-10-02 03:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_mechanic_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="product",
            name="motors",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
        migrations.AddField(
            model_name="product",
            name="part",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="product_part",
                to="myapp.sparepart",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="piece_count",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="product",
            name="generic",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
