# Generated by Django 4.1.7 on 2023-12-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0007_alter_product_label_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="label_format",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
