# Generated by Django 4.1.7 on 2023-10-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_product_brand_product_motors_product_part_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="purchase_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
