# Generated by Django 4.1.7 on 2023-12-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0008_sparepart_label_format"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sparepart",
            name="label_format",
            field=models.CharField(
                blank=True, default="P8, D16, B10, T8", max_length=50
            ),
        ),
    ]
