# Generated by Django 4.1.7 on 2023-10-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0010_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_orig",
            field=models.BooleanField(default=False),
        ),
    ]
