# Generated by Django 4.1.7 on 2023-10-11 03:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0012_product_quantity_alter_product_motors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
