# Generated by Django 4.1.7 on 2023-10-12 20:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0013_remove_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="is_motor_shown",
            field=models.BooleanField(default=True),
        ),
    ]
