# Generated by Django 4.1.7 on 2023-10-14 02:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0015_product_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="quantity",
        ),
    ]
