# Generated by Django 4.1.7 on 2023-10-16 15:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0016_remove_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="sparepart",
            name="is_semi_shown",
            field=models.BooleanField(default=False),
        ),
    ]
