# Generated by Django 4.1.7 on 2023-10-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0017_sparepart_is_semi_shown"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="to_print",
            field=models.BooleanField(default=False),
        ),
    ]
