# Generated by Django 4.1.7 on 2023-10-20 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0018_product_to_print"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="to_print",
        ),
        migrations.AddField(
            model_name="product",
            name="print_count",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
