# Generated by Django 4.1.7 on 2023-11-06 04:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0020_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "datetime_opened",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("datetime_closed", models.DateTimeField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_mode1",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_mode1",
                        to="myapp.account",
                    ),
                ),
                (
                    "payment_mode2",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payment_mode2",
                        to="myapp.account",
                    ),
                ),
                (
                    "user_adder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_user_adder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_closer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_user_closer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_validator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sales_user_validator",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_description", models.CharField(default="", max_length=200)),
                (
                    "quantity_sold",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "quantity_returned",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_claimed", models.BooleanField(default=False)),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "datetime_added",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("datetime_claimed", models.DateTimeField(blank=True)),
                (
                    "sales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sales_item",
                        to="myapp.sales",
                    ),
                ),
                (
                    "user_adder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_user_adder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_giver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="item_user_giver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LaborItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("labor_name", models.CharField(default="", max_length=200)),
                ("is_done", models.BooleanField(default=False)),
                (
                    "unit_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "datetime_added",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("datetime_done", models.DateTimeField(blank=True)),
                (
                    "mechanic",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labor_mechanic",
                        to="myapp.mechanic",
                    ),
                ),
                (
                    "sales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labor_item",
                        to="myapp.sales",
                    ),
                ),
                (
                    "user_adder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labor_user_adder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_giver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="labor_user_giver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
