# Generated by Django 4.1.7 on 2023-11-06 04:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0021_sales_salesitem_laboritem"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Sales",
            new_name="Sale",
        ),
    ]
