# Generated by Django 4.1.7 on 2023-11-06 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0022_rename_sales_sale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="sale",
            old_name="discount_amount",
            new_name="discount",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="paid_amount",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="payment_mode1",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="payment_mode2",
        ),
        migrations.CreateModel(
            name="Transaction2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(default="", max_length=200)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction2_category",
                        to="myapp.category",
                    ),
                ),
                (
                    "encoder",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction2_encoder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction2_receiver",
                        to="myapp.account",
                    ),
                ),
                (
                    "transmitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaction2_transmitter",
                        to="myapp.account",
                    ),
                ),
            ],
        ),
    ]
