# Generated by Django 4.1.7 on 2023-11-06 05:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0024_alter_salesitem_unit_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salesitem",
            name="unit_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
