# Generated by Django 4.1.7 on 2023-11-06 05:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0025_alter_salesitem_unit_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "supplier_name",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "datetime_opened",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("datetime_closed", models.DateTimeField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "user_adder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_user_adder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_closer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_user_closer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="salesitem",
            name="item_description",
        ),
        migrations.AddField(
            model_name="salesitem",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_product",
                to="myapp.product",
            ),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="user_adder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_item_user_adder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="user_giver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sales_item_user_giver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="PurchaseItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("is_claimed", models.BooleanField(default=False)),
                (
                    "purchase_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=7,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "datetime_added",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "product",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_product",
                        to="myapp.product",
                    ),
                ),
                (
                    "sales",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_item",
                        to="myapp.purchase",
                    ),
                ),
                (
                    "user_adder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchase_item_user_adder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
