# Generated by Django 4.1.7 on 2023-11-06 05:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0026_purchase_remove_salesitem_item_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="salesitem",
            old_name="unit_amount",
            new_name="selling_price",
        ),
    ]
