# Generated by Django 4.1.7 on 2023-11-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0028_rename_quantity_sold_salesitem_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laboritem",
            name="datetime_done",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="purchase",
            name="datetime_closed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sale",
            name="datetime_closed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="salesitem",
            name="datetime_claimed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
