# Generated by Django 4.1.7 on 2023-11-11 00:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0029_alter_laboritem_datetime_done_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseitem",
            old_name="sales",
            new_name="purchase",
        ),
        migrations.RemoveField(
            model_name="purchaseitem",
            name="purchase_price",
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="datetime_claimed",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="selling_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="user_giver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchase_item_user_giver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
