# Generated by Django 4.1.7 on 2023-11-11 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0030_rename_sales_purchaseitem_purchase_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="laboritem",
            name="unit_amount",
        ),
        migrations.AddField(
            model_name="laboritem",
            name="amount_owed",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="laboritem",
            name="amount_received",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="laboritem",
            name="amount_returned",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
