# Generated by Django 4.1.7 on 2023-11-11 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0031_remove_laboritem_unit_amount_laboritem_amount_owed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="laboritem",
            name="amount_owed",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="laboritem",
            name="amount_received",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="laboritem",
            name="amount_returned",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
