# Generated by Django 4.1.7 on 2023-11-11 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0032_alter_laboritem_amount_owed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payment_sales",
                to="myapp.transaction2",
            ),
        ),
    ]
