# Generated by Django 4.1.7 on 2023-11-11 01:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0033_sale_payment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="payment",
        ),
        migrations.AddField(
            model_name="sale",
            name="payment",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="payment_sales",
                to="myapp.transaction2",
            ),
        ),
    ]
