# Generated by Django 4.1.7 on 2023-11-11 02:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0035_alter_sale_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="salesitem",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
