# Generated by Django 4.1.7 on 2023-11-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0036_salesitem_description_salesitem_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="to_print",
            field=models.BooleanField(default=False),
        ),
    ]
