# Generated by Django 4.1.7 on 2023-11-12 02:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0037_sale_to_print"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction2",
            name="datetime_transacted",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
