# Generated by Django 4.1.7 on 2023-11-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0038_transaction2_datetime_transacted"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="status",
            field=models.CharField(
                choices=[("1", "none"), ("2", "proc"), ("3", "paid")],
                default="1",
                max_length=10,
            ),
        ),
    ]
