# Generated by Django 4.1.7 on 2023-11-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0039_sale_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="nature",
            field=models.CharField(
                choices=[
                    ("1", "Expense"),
                    ("2", "Income"),
                    ("3", "Transfer"),
                    ("4", "Payable"),
                    ("5", "Receivable"),
                ],
                default="3",
                max_length=20,
            ),
        ),
    ]
