# Generated by Django 4.1.7 on 2023-11-14 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0040_alter_category_nature"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="returneditem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="returneditem",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
