# Generated by Django 4.1.7 on 2023-11-14 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0041_alter_category_options_returneditem_description_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="returneditem",
            old_name="price",
            new_name="selling_price",
        ),
    ]
