# Generated by Django 4.1.7 on 2023-11-14 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0042_rename_price_returneditem_selling_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receivable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "borrower_name",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "datetime_opened",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "datetime_due",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("datetime_closed", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payment",
                    models.ManyToManyField(
                        blank=True,
                        related_name="payment_receivable",
                        to="myapp.transaction2",
                    ),
                ),
                (
                    "user_closer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receivable_user_closer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_opener",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receivable_user_adder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Payable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lender_name",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                (
                    "datetime_opened",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "datetime_due",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("datetime_closed", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "payment",
                    models.ManyToManyField(
                        blank=True,
                        related_name="payment_payable",
                        to="myapp.transaction2",
                    ),
                ),
                (
                    "user_closer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payable_user_closer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user_opener",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="payable_user_adder",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
