# Generated by Django 4.1.7 on 2023-11-14 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0043_receivable_payable"),
    ]

    operations = [
        migrations.AddField(
            model_name="payable",
            name="borrowed_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="receivable",
            name="lent_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
