# Generated by Django 4.1.7 on 2023-11-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0044_payable_borrowed_amount_receivable_lent_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payable",
            name="datetime_due",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="receivable",
            name="datetime_due",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
