# Generated by Django 4.1.7 on 2023-11-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0045_alter_payable_datetime_due_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payable",
            name="receipt",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AddField(
            model_name="receivable",
            name="receipt",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
