# Generated by Django 4.1.7 on 2023-11-14 12:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0046_payable_receipt_receivable_receipt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payable",
            old_name="receipt",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="receivable",
            old_name="receipt",
            new_name="description",
        ),
    ]
