# Generated by Django 4.1.7 on 2023-11-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0048_alter_purchaseitem_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="status",
            field=models.CharField(
                choices=[("1", "EDIT"), ("2", "PEND"), ("3", "PROC"), ("4", "DONE")],
                default="1",
                max_length=20,
            ),
        ),
    ]
