# Generated by Django 4.1.7 on 2023-11-22 12:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0049_purchase_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="purchaseitem",
            old_name="selling_price",
            new_name="purchase_price",
        ),
    ]
