# Generated by Django 4.1.7 on 2023-11-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0050_rename_selling_price_purchaseitem_purchase_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="description",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
