# Generated by Django 4.1.7 on 2023-11-23 00:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0051_purchaseitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="unit",
            field=models.CharField(default="PC", max_length=10),
        ),
    ]
