# Generated by Django 4.1.7 on 2023-11-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0052_purchaseitem_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="to_print",
            field=models.BooleanField(default=False),
        ),
    ]
