# Generated by Django 4.1.7 on 2023-11-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0053_purchase_to_print"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseitem",
            name="is_claimed",
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="is_valid",
            field=models.BooleanField(default=True),
        ),
    ]
