# Generated by Django 4.1.7 on 2023-11-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0054_remove_purchaseitem_is_claimed_purchaseitem_is_valid"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="datetime_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
